namespace :db do
 require "sequel"
 require "pg"
 Sequel.extension :migration


 # evaluate_test_result task - evaluate test result (testing purpose only)  
 desc "Rake task 1 Inner...."
 task :innerTask1 do
  puts "Evaluating inner task1 ...."
 end 

end
